AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Escola de software - Blog - Delete BlogPost - Lambda Function
Parameters:
  Environment:
    Description: Environment
    Type: String
  S3BucketName:
    Description: S3 Bucket Name
    Type: String
  BlogPostTableDeleteItemPolicy:
    Description: BlogPost Table Policy
    Type: String
  BlogPostTableGetItemPolicy:
    Description: BlogPost Table Policy
    Type: String

Resources:
  BlogPostBucketDeleteObjectPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for DeleteObject on S3 Bucket
      ManagedPolicyName:
        !Join [
          "_",
          [!Ref Environment, "BlogPostBucketDeleteObjectPolicy", "Policy"],
        ]
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "s3:DeleteObject"
            Resource:
              !Join [
                "",
                [
                  "arn:aws:s3:::",
                  !Ref Environment,
                  "-",
                  !Ref S3BucketName,
                  "/*",
                ],
              ]

  DeleteBlogPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["_", [!Ref Environment, DeleteBlogPostFn]]
      Description: Delete Blogpost function
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Timeout: 1
      Policies:
        - !Ref BlogPostBucketDeleteObjectPolicy
        - Fn::Join:
            [
              "",
              [
                "arn:aws:iam::",
                !Sub "${AWS::AccountId}",
                ":policy/",
                !Ref BlogPostTableDeleteItemPolicy,
              ],
            ]
        - Fn::Join:
            [
              "",
              [
                "arn:aws:iam::",
                !Sub "${AWS::AccountId}",
                ":policy/",
                !Ref BlogPostTableGetItemPolicy,
              ],
            ]
      Environment:
        Variables:
          BlogPostContentBucketName:
            !Join ["-", [!Ref Environment, !Ref S3BucketName]]
          BlogPostTableName:
            Fn::Join: ["_", [!Ref Environment, escoladesoftware_blog_blogpost]]
          Region: us-east-1
